version: "3.8"
services:
  db:
    image: mongo:7.0.5-jammy
    container_name: coleccionista-bd-test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=myPassword123
    ports:
      - 27017:27017
    volumes:
      - mongodb_Coleccionista:/data/db
      - mongodb_config_Coleccionista:/data/configdb
    networks:
      - Coleccionista_net

  api:
    container_name: coleccionista-api-test
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./api:/code/
    ports:
      - "8000:80"

    depends_on:
      - db
    networks:
      - Coleccionista_net

  mobile:
    container_name: web-coleccionista-ionic
    build: ./coleccti-mate
    command: ionic serve --host=0.0.0.0 --port=8100
    volumes:
      - ./coleccti-mate:/code/coleccti-mate
    ports:
      - "8100:8100"
    depends_on:
      - api
    working_dir: /code/coleccti-mate
    networks:
      - Coleccionista_net

networks:
  Coleccionista_net:
