services:
  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: coleccionista-bd-oracle-test
    environment:
      - ORACLE_PWD=myPassword123
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle_db_volume:/opt/oracle/oradata
    networks:
      - Coleccionista_net

  api:
    container_name: coleccionista-api-test
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./api:/code/
    ports:
      - "8000:80"

    depends_on:
      - db
    networks:
      - Coleccionista_net

networks:
  Coleccionista_net:
volumes:
  oracle_db_volume:
