version: "3.8"
services:
  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: coleccionista-bd-oracle-test
    environment:
      - ORACLE_PWD=myPassword123
    healthcheck: # check if the db is ready to accept connections
      test: ["CMD", "bash", "-c", "echo exit | sqlplus -L system/myPassword123@localhost:1521/xe"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 2m
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle_db_volume:/opt/oracle/oradata
    networks:
      - Coleccionista_net

  api:
    container_name: coleccionista-api-test
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./api:/code/
    ports:
      - "8000:80"

    depends_on:
      db:
        condition: service_healthy # wait for the db to be healthy (in relation to the healthcheck above)
    networks:
      - Coleccionista_net

  mobile:
    container_name: web-ionic-api-test
    build: ./collecti-mate
    command: ionic serve --host=0.0.0.0 --port=8100
    volumes:
      - ./collecti-mate:/code/collecti-mate
    ports:
      - "8100:8100"
    depends_on:
      - api
    working_dir: /code/collecti-mate
    networks:
      - Coleccionista_net

networks:
  Coleccionista_net:
volumes:
  oracle_db_volume:
